version: 2.1

machine: true

jobs:
  build:
    executor: my-ubuntu-exec
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      - run:
          name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
          with:
            install: true
      - run:
          name: Install OCI CLI
          command: |
            mkdir ~/.oci
            echo "${{ OCI_CONFIG }}" > ~/.oci/config
            echo "${{ OCI_KEY_FILE }}" > ~/.oci/key.pem
            curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
            chmod +x install.sh
            ./install.sh --accept-all-defaults
            echo "/home/runner/bin" >> $GITHUB_PATH
            exec -l $SHELL
            oci setup repair-file-permissions --file /home/runner/.oci/config
            oci setup repair-file-permissions --file /home/runner/.oci/key.pem
      - run:
          name: Install kubectl
          command: |
            mkdir /tmp/.kube
            curl -L -O "https://dl.k8s.io/release/v1.22.4/bin/linux/amd64/kubectl" -o kubectl
            chmod +x kubectl
            mv kubectl /usr/local/bin
            echo "${{ KUBECONFIG }}" > /tmp/.kube/config
            echo "KUBECONFIG=/tmp/.kube/config" >> $GITHUB_ENV
      - run:
          name: Currently running services
          command: kubectl -n default get pods
      - run:
          name: Login to Docker registry
          uses: docker/login-action@v1
          with:
            registry: ${{ DOCKER_URL }}
            username: ${{ DOCKER_USERNAME }}
            password: ${{ DOCKER_PASSWORD }}
      - run:
          name: Available platforms
          run: echo ${{ steps.buildx.outputs.platforms }}
      - run:
          name: Build
          command: |
            docker build --push --platform linux/amd64,linux/arm64 -t ${{ DOCKER_URL }}/${{ DOCKER_OBJECT_STORAGE_NAMESPACE }}/kubernetes-sample-app:latest kube/.
      - run:
          name: Deploy to Kubernetes Sample App
          command: |
            sed -i 's/<DOCKER_OBJECT_STORAGE_NAMESPACE>/${{ DOCKER_OBJECT_STORAGE_NAMESPACE }}/g' kube/sample-deployment.yaml
            kubectl -n default apply -f kube/sample-deployment.yaml
      - run:
          name: Restart kubernetes sample app
          command: |
            kubectl -n default rollout restart deployment kubernetes-sample-app

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master